-- =============================================================
-- GEARNOVA - SUPABASE SETUP
-- Chạy TOÀN BỘ file này trong Supabase > SQL Editor, một lần.
-- =============================================================

-- 1) HỒ SƠ NGƯỜI DÙNG
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'user',
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user', 'admin'));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      new.raw_user_meta_data ->> 'full_name',
      split_part(coalesce(new.email, 'user'), '@', 1)
    ),
    'user'
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = coalesce(public.profiles.display_name, excluded.display_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Bù profile cho các tài khoản đã tồn tại.
insert into public.profiles (id, email, display_name, role)
select
  u.id,
  u.email,
  coalesce(
    u.raw_user_meta_data ->> 'display_name',
    u.raw_user_meta_data ->> 'full_name',
    split_part(coalesce(u.email, 'user'), '@', 1)
  ),
  'user'
from auth.users u
on conflict (id) do update set
  email = excluded.email,
  display_name = coalesce(public.profiles.display_name, excluded.display_name);

-- 2) SẢN PHẨM
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price bigint not null default 0,
  image_url text,
  description text not null default '',
  specs jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists name text;
alter table public.products add column if not exists category text;
alter table public.products add column if not exists price bigint not null default 0;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists description text not null default '';
alter table public.products add column if not exists specs jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.products add column if not exists created_at timestamptz not null default now();

-- Chuẩn hóa dữ liệu cũ từ bản dùng VGA / Gear và các giá trị cũ khác.
update public.products set category = upper(trim(category)) where category is not null;
update public.products set category = 'GPU' where category = 'VGA';
update public.products set category = 'GEAR'
where category is null or category not in ('CPU', 'GPU', 'RAM', 'SSD', 'GEAR');

alter table public.products drop constraint if exists products_category_check;
alter table public.products add constraint products_category_check
  check (category in ('CPU', 'GPU', 'RAM', 'SSD', 'GEAR'));
alter table public.products drop constraint if exists products_price_check;
alter table public.products add constraint products_price_check check (price >= 0);

create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists products_category_idx on public.products (category);

-- 3) HÀM QUYỀN QUẢN TRỊ
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 4) RLS: người dùng chỉ đọc profile của chính mình;
--          người đã đăng nhập được xem sản phẩm;
--          chỉ admin được thêm/xóa/sửa sản phẩm.
alter table public.profiles enable row level security;
alter table public.products enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select to authenticated
  using (id = auth.uid());

drop policy if exists "products_select_authenticated" on public.products;
drop policy if exists "products_insert_admin" on public.products;
drop policy if exists "products_update_admin" on public.products;
drop policy if exists "products_delete_admin" on public.products;

create policy "products_select_authenticated"
  on public.products for select to authenticated using (true);

create policy "products_insert_admin"
  on public.products for insert to authenticated
  with check (public.is_admin());

create policy "products_update_admin"
  on public.products for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "products_delete_admin"
  on public.products for delete to authenticated
  using (public.is_admin());

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 5) SẢN PHẨM MẪU: chỉ thêm nếu bảng đang trống.
insert into public.products (name, category, price, description, specs)
select * from (
  values
    ('AMD Ryzen 5 7600', 'CPU', 4890000, 'CPU 6 nhân 12 luồng nền tảng AM5, phù hợp gaming Full HD và đa nhiệm.', '["6 nhân / 12 luồng", "Socket AM5", "Zen 4", "TDP 65W"]'::jsonb),
    ('Intel Core i7-14700F', 'CPU', 9290000, 'Hiệu năng mạnh cho gaming, dựng hình và workstation phổ thông.', '["20 nhân / 28 luồng", "Socket LGA1700", "Không tích hợp GPU"]'::jsonb),
    ('ASUS Dual GeForce RTX 4060 OC 8GB', 'GPU', 8290000, 'Card đồ họa RTX 4060 cho game Full HD với Ray Tracing và DLSS 3.', '["8GB GDDR6", "Ray Tracing", "DLSS 3"]'::jsonb),
    ('Gigabyte RTX 4070 SUPER Gaming OC 12GB', 'GPU', 17990000, 'Lựa chọn mạnh cho gaming độ phân giải 2K và làm đồ họa.', '["12GB GDDR6X", "Triple Fan", "DLSS 3"]'::jsonb),
    ('Kingston Fury Beast 32GB DDR5 Kit', 'RAM', 2490000, 'Bộ RAM DDR5 32GB cân bằng cho game, thiết kế và công việc đa nhiệm.', '["32GB (2 x 16GB)", "DDR5", "Dual Channel"]'::jsonb),
    ('Samsung 990 PRO 2TB NVMe', 'SSD', 4590000, 'SSD NVMe PCIe 4.0 tốc độ cao cho game và workstation.', '["2TB", "M.2 NVMe", "PCIe 4.0"]'::jsonb),
    ('Keychron K2 Pro Mechanical Keyboard', 'GEAR', 2390000, 'Bàn phím cơ 75% nhỏ gọn, kết nối không dây và USB-C.', '["Layout 75%", "Mechanical", "Bluetooth"]'::jsonb),
    ('Logitech G502 X Gaming Mouse', 'GEAR', 1890000, 'Chuột gaming công thái học với cảm biến chính xác và nút tùy biến.', '["Gaming Sensor", "Nút lập trình", "Ergonomic"]'::jsonb)
) as seed(name, category, price, description, specs)
where not exists (select 1 from public.products);

-- 6) QUẢN TRỊ BẰNG MẬT KHẨU CỐ ĐỊNH
-- Mật khẩu hiện tại: GearNova@2026
-- Nếu muốn đổi, phải đổi cả trong file index.js.
-- Các hàm này cho phép website thêm/xóa sản phẩm mà không cần cấp role admin
-- cho từng email. Chỉ tài khoản đã đăng nhập và có đúng mật khẩu mới gọi được.
create or replace function public.admin_add_product(
  p_admin_password text,
  p_name text,
  p_category text,
  p_price bigint,
  p_image_url text,
  p_description text,
  p_specs jsonb
)
returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
  created_product public.products;
begin
  if p_admin_password <> 'GearNova@2026' then
    raise exception 'Sai mật khẩu quản trị.';
  end if;

  if coalesce(p_category, '') not in ('CPU', 'GPU', 'RAM', 'SSD', 'GEAR') then
    raise exception 'Danh mục không hợp lệ.';
  end if;

  if coalesce(btrim(p_name), '') = '' or p_price is null or p_price < 0 then
    raise exception 'Dữ liệu sản phẩm không hợp lệ.';
  end if;

  insert into public.products (name, category, price, image_url, description, specs)
  values (
    btrim(p_name),
    p_category,
    p_price,
    nullif(btrim(coalesce(p_image_url, '')), ''),
    coalesce(p_description, ''),
    coalesce(p_specs, '[]'::jsonb)
  )
  returning * into created_product;

  return created_product;
end;
$$;

create or replace function public.admin_delete_product(
  p_admin_password text,
  p_product_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_admin_password <> 'GearNova@2026' then
    raise exception 'Sai mật khẩu quản trị.';
  end if;

  delete from public.products where id = p_product_id;
end;
$$;

revoke all on function public.admin_add_product(text, text, text, bigint, text, text, jsonb) from public;
revoke all on function public.admin_delete_product(text, bigint) from public;
grant execute on function public.admin_add_product(text, text, text, bigint, text, text, jsonb) to authenticated;
grant execute on function public.admin_delete_product(text, bigint) to authenticated;
